name: galactic_scales
description: A new Flutter project.

publish_to: 'none' 

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  auto_route: ^7.8.4
  url_launcher: ^6.2.1
  percent_indicator: ^4.2.3
  carousel_slider: ^4.2.1
  getwidget: ^4.0.0
  intl: ^0.19.0
  flutter_native_splash: ^2.3.10
  flutter_launcher_icons: ^0.13.1
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.2

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: assets/images/planet.png

flutter_native_splash:
  android: true
  fullscreen: true
  color: "#808080"
  image: assets/images/planet.png

  android_12:
    color: "#808080"
    image: assets/images/planet.png

flutter:
  assets:
    - assets/data/data.json
    - assets/data/quiz_data.json

  uses-material-design: true

